[package]
name = "rstreamer-transform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstreamer-core = {path="../rstreamer-core"}

fast_image_resize = "^2.7"